#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsedEquipmentSln.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_SHARE")]
	public partial class DtClass_DBShareDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_DWH_DISTRICT(TBL_DWH_DISTRICT instance);
    partial void UpdateTBL_DWH_DISTRICT(TBL_DWH_DISTRICT instance);
    partial void DeleteTBL_DWH_DISTRICT(TBL_DWH_DISTRICT instance);
    partial void InsertTBL_DWH_DEPARTMENT(TBL_DWH_DEPARTMENT instance);
    partial void UpdateTBL_DWH_DEPARTMENT(TBL_DWH_DEPARTMENT instance);
    partial void DeleteTBL_DWH_DEPARTMENT(TBL_DWH_DEPARTMENT instance);
    #endregion
		
		public DtClass_DBShareDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_SHAREConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_DBShareDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_DBShareDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_DBShareDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_DBShareDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_DWH_DISTRICT> TBL_DWH_DISTRICTs
		{
			get
			{
				return this.GetTable<TBL_DWH_DISTRICT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DWH_DEPARTMENT> TBL_DWH_DEPARTMENTs
		{
			get
			{
				return this.GetTable<TBL_DWH_DEPARTMENT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DWH_DIVISION> TBL_DWH_DIVISIONs
		{
			get
			{
				return this.GetTable<TBL_DWH_DIVISION>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DWH_DISTRICT")]
	public partial class TBL_DWH_DISTRICT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DSTRCT_CODE;
		
		private string _DSTRCT_NAME;
		
		private string _DSTRCT_STATUS;
		
		private string _PLANT_AREA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDSTRCT_CODEChanging(string value);
    partial void OnDSTRCT_CODEChanged();
    partial void OnDSTRCT_NAMEChanging(string value);
    partial void OnDSTRCT_NAMEChanged();
    partial void OnDSTRCT_STATUSChanging(string value);
    partial void OnDSTRCT_STATUSChanged();
    partial void OnPLANT_AREAChanging(string value);
    partial void OnPLANT_AREAChanged();
    #endregion
		
		public TBL_DWH_DISTRICT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this.OnDSTRCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_CODE = value;
					this.SendPropertyChanged("DSTRCT_CODE");
					this.OnDSTRCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_NAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DSTRCT_NAME
		{
			get
			{
				return this._DSTRCT_NAME;
			}
			set
			{
				if ((this._DSTRCT_NAME != value))
				{
					this.OnDSTRCT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_NAME = value;
					this.SendPropertyChanged("DSTRCT_NAME");
					this.OnDSTRCT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_STATUS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DSTRCT_STATUS
		{
			get
			{
				return this._DSTRCT_STATUS;
			}
			set
			{
				if ((this._DSTRCT_STATUS != value))
				{
					this.OnDSTRCT_STATUSChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_STATUS = value;
					this.SendPropertyChanged("DSTRCT_STATUS");
					this.OnDSTRCT_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLANT_AREA", DbType="VarChar(10)")]
		public string PLANT_AREA
		{
			get
			{
				return this._PLANT_AREA;
			}
			set
			{
				if ((this._PLANT_AREA != value))
				{
					this.OnPLANT_AREAChanging(value);
					this.SendPropertyChanging();
					this._PLANT_AREA = value;
					this.SendPropertyChanged("PLANT_AREA");
					this.OnPLANT_AREAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DWH_DEPARTMENT")]
	public partial class TBL_DWH_DEPARTMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DSTRCT_CODE;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _DIV_CODE;
		
		private string _DIV_DESC;
		
		private string _DEPT_NAME;
		
		private string _DISTRICT_CODE;
		
		private string _DEPT_CODE_DESC;
		
		private string _DIV_CODE_DESC;
		
		private string _ID_DEPT;
		
		private string _DEPT_CODE_DESC_INITCAP;
		
		private string _DIV_CODE_DESC_INITCAP;
		
		private System.Nullable<System.DateTime> _CREATION_DATE;
		
		private System.Nullable<System.DateTime> _MODIFIED_DATE;
		
		private string _DEPT_CODE_V1;
		
		private System.Nullable<int> _DEPT_CODE_V2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDSTRCT_CODEChanging(string value);
    partial void OnDSTRCT_CODEChanged();
    partial void OnDEPT_CODEChanging(string value);
    partial void OnDEPT_CODEChanged();
    partial void OnDEPT_DESCChanging(string value);
    partial void OnDEPT_DESCChanged();
    partial void OnDIV_CODEChanging(string value);
    partial void OnDIV_CODEChanged();
    partial void OnDIV_DESCChanging(string value);
    partial void OnDIV_DESCChanged();
    partial void OnDEPT_NAMEChanging(string value);
    partial void OnDEPT_NAMEChanged();
    partial void OnDISTRICT_CODEChanging(string value);
    partial void OnDISTRICT_CODEChanged();
    partial void OnDEPT_CODE_DESCChanging(string value);
    partial void OnDEPT_CODE_DESCChanged();
    partial void OnDIV_CODE_DESCChanging(string value);
    partial void OnDIV_CODE_DESCChanged();
    partial void OnID_DEPTChanging(string value);
    partial void OnID_DEPTChanged();
    partial void OnDEPT_CODE_DESC_INITCAPChanging(string value);
    partial void OnDEPT_CODE_DESC_INITCAPChanged();
    partial void OnDIV_CODE_DESC_INITCAPChanging(string value);
    partial void OnDIV_CODE_DESC_INITCAPChanged();
    partial void OnCREATION_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATION_DATEChanged();
    partial void OnMODIFIED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFIED_DATEChanged();
    partial void OnDEPT_CODE_V1Changing(string value);
    partial void OnDEPT_CODE_V1Changed();
    partial void OnDEPT_CODE_V2Changing(System.Nullable<int> value);
    partial void OnDEPT_CODE_V2Changed();
    #endregion
		
		public TBL_DWH_DEPARTMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this.OnDSTRCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_CODE = value;
					this.SendPropertyChanged("DSTRCT_CODE");
					this.OnDSTRCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this.OnDEPT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CODE = value;
					this.SendPropertyChanged("DEPT_CODE");
					this.OnDEPT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(50)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this.OnDEPT_DESCChanging(value);
					this.SendPropertyChanging();
					this._DEPT_DESC = value;
					this.SendPropertyChanged("DEPT_DESC");
					this.OnDEPT_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this.OnDIV_CODEChanging(value);
					this.SendPropertyChanging();
					this._DIV_CODE = value;
					this.SendPropertyChanged("DIV_CODE");
					this.OnDIV_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_DESC", DbType="VarChar(50)")]
		public string DIV_DESC
		{
			get
			{
				return this._DIV_DESC;
			}
			set
			{
				if ((this._DIV_DESC != value))
				{
					this.OnDIV_DESCChanging(value);
					this.SendPropertyChanging();
					this._DIV_DESC = value;
					this.SendPropertyChanged("DIV_DESC");
					this.OnDIV_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_NAME", DbType="VarChar(50)")]
		public string DEPT_NAME
		{
			get
			{
				return this._DEPT_NAME;
			}
			set
			{
				if ((this._DEPT_NAME != value))
				{
					this.OnDEPT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_NAME = value;
					this.SendPropertyChanged("DEPT_NAME");
					this.OnDEPT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRICT_CODE", DbType="VarChar(4)")]
		public string DISTRICT_CODE
		{
			get
			{
				return this._DISTRICT_CODE;
			}
			set
			{
				if ((this._DISTRICT_CODE != value))
				{
					this.OnDISTRICT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DISTRICT_CODE = value;
					this.SendPropertyChanged("DISTRICT_CODE");
					this.OnDISTRICT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_DESC", DbType="VarChar(50)")]
		public string DEPT_CODE_DESC
		{
			get
			{
				return this._DEPT_CODE_DESC;
			}
			set
			{
				if ((this._DEPT_CODE_DESC != value))
				{
					this.OnDEPT_CODE_DESCChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CODE_DESC = value;
					this.SendPropertyChanged("DEPT_CODE_DESC");
					this.OnDEPT_CODE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE_DESC", DbType="VarChar(50)")]
		public string DIV_CODE_DESC
		{
			get
			{
				return this._DIV_CODE_DESC;
			}
			set
			{
				if ((this._DIV_CODE_DESC != value))
				{
					this.OnDIV_CODE_DESCChanging(value);
					this.SendPropertyChanging();
					this._DIV_CODE_DESC = value;
					this.SendPropertyChanged("DIV_CODE_DESC");
					this.OnDIV_CODE_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DEPT", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_DEPT
		{
			get
			{
				return this._ID_DEPT;
			}
			set
			{
				if ((this._ID_DEPT != value))
				{
					this.OnID_DEPTChanging(value);
					this.SendPropertyChanging();
					this._ID_DEPT = value;
					this.SendPropertyChanged("ID_DEPT");
					this.OnID_DEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_DESC_INITCAP", DbType="VarChar(50)")]
		public string DEPT_CODE_DESC_INITCAP
		{
			get
			{
				return this._DEPT_CODE_DESC_INITCAP;
			}
			set
			{
				if ((this._DEPT_CODE_DESC_INITCAP != value))
				{
					this.OnDEPT_CODE_DESC_INITCAPChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CODE_DESC_INITCAP = value;
					this.SendPropertyChanged("DEPT_CODE_DESC_INITCAP");
					this.OnDEPT_CODE_DESC_INITCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE_DESC_INITCAP", DbType="VarChar(50)")]
		public string DIV_CODE_DESC_INITCAP
		{
			get
			{
				return this._DIV_CODE_DESC_INITCAP;
			}
			set
			{
				if ((this._DIV_CODE_DESC_INITCAP != value))
				{
					this.OnDIV_CODE_DESC_INITCAPChanging(value);
					this.SendPropertyChanging();
					this._DIV_CODE_DESC_INITCAP = value;
					this.SendPropertyChanged("DIV_CODE_DESC_INITCAP");
					this.OnDIV_CODE_DESC_INITCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this.OnCREATION_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATION_DATE = value;
					this.SendPropertyChanged("CREATION_DATE");
					this.OnCREATION_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFIED_DATE
		{
			get
			{
				return this._MODIFIED_DATE;
			}
			set
			{
				if ((this._MODIFIED_DATE != value))
				{
					this.OnMODIFIED_DATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFIED_DATE = value;
					this.SendPropertyChanged("MODIFIED_DATE");
					this.OnMODIFIED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_V1", DbType="VarChar(4)")]
		public string DEPT_CODE_V1
		{
			get
			{
				return this._DEPT_CODE_V1;
			}
			set
			{
				if ((this._DEPT_CODE_V1 != value))
				{
					this.OnDEPT_CODE_V1Changing(value);
					this.SendPropertyChanging();
					this._DEPT_CODE_V1 = value;
					this.SendPropertyChanged("DEPT_CODE_V1");
					this.OnDEPT_CODE_V1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_V2", DbType="Int")]
		public System.Nullable<int> DEPT_CODE_V2
		{
			get
			{
				return this._DEPT_CODE_V2;
			}
			set
			{
				if ((this._DEPT_CODE_V2 != value))
				{
					this.OnDEPT_CODE_V2Changing(value);
					this.SendPropertyChanging();
					this._DEPT_CODE_V2 = value;
					this.SendPropertyChanged("DEPT_CODE_V2");
					this.OnDEPT_CODE_V2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DWH_DIVISION")]
	public partial class TBL_DWH_DIVISION
	{
		
		private string _DIV_CODE;
		
		private string _DIV_CODE_DESC;
		
		private string _DIV_CODE_DESC_INITCAP;
		
		private System.Nullable<System.DateTime> _CREATION_DATE;
		
		private System.Nullable<System.DateTime> _MODIFIED_DATE;
		
		public TBL_DWH_DIVISION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this._DIV_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE_DESC", DbType="VarChar(50)")]
		public string DIV_CODE_DESC
		{
			get
			{
				return this._DIV_CODE_DESC;
			}
			set
			{
				if ((this._DIV_CODE_DESC != value))
				{
					this._DIV_CODE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE_DESC_INITCAP", DbType="VarChar(50)")]
		public string DIV_CODE_DESC_INITCAP
		{
			get
			{
				return this._DIV_CODE_DESC_INITCAP;
			}
			set
			{
				if ((this._DIV_CODE_DESC_INITCAP != value))
				{
					this._DIV_CODE_DESC_INITCAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATION_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATION_DATE
		{
			get
			{
				return this._CREATION_DATE;
			}
			set
			{
				if ((this._CREATION_DATE != value))
				{
					this._CREATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFIED_DATE
		{
			get
			{
				return this._MODIFIED_DATE;
			}
			set
			{
				if ((this._MODIFIED_DATE != value))
				{
					this._MODIFIED_DATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
